import { CategoryType, Product, QuickCategory } from './types';
import { ShoppingBag, Zap, Utensils, Activity, Smartphone, Sparkles, Shirt, Home, Gamepad2 } from 'lucide-react';
import React from 'react';

// --- Branding ---
// REPLACE THIS URL WITH YOUR UPLOADED LOGO URL
export const APP_LOGO = "https://cdn-icons-png.flaticon.com/512/3737/3737372.png";

// --- Helper Data for UI Sections ---

export const FOOD_CUISINES: QuickCategory[] = [
  { id: 'c1', label: 'Biryani', image: 'https://b.zmtcdn.com/data/dish_images/d19a31d42d5913ff129cafd7cec772f51639658624.png' },
  { id: 'c2', label: 'Pizza', image: 'https://b.zmtcdn.com/data/o2_assets/d0bd7c9405ac87f6aa65e31fe55800941632716575.png' },
  { id: 'c3', label: 'Burger', image: 'https://b.zmtcdn.com/data/dish_images/ccb7dc653753e83d63065d7f495a8c101639733140.png' },
  { id: 'c4', label: 'Thali', image: 'https://b.zmtcdn.com/data/dish_images/197987b7ebcd1ee08f8c25ea4e77e20f1634731334.png' },
  { id: 'c5', label: 'Chicken', image: 'https://b.zmtcdn.com/data/dish_images/1437bc204cb5c892cb22d78b4347f4651634827140.png' },
  { id: 'c6', label: 'Cake', image: 'https://b.zmtcdn.com/data/dish_images/d5ab931c8c239271de45e1c159af94311634805744.png' },
];

// Expanded Grocery Categories (Zepto/Blinkit Style)
export const GROCERY_CATEGORIES: QuickCategory[] = [
  { id: 'gc1', label: 'Veg & Fruits', image: 'https://cdn.grofers.com/app/images/category/cms_images/icon/icon_cat_1487_v_3_500_1643383030565.png' },
  { id: 'gc2', label: 'Dairy & Bread', image: 'https://cdn.grofers.com/app/images/category/cms_images/icon/icon_cat_14_v_3_500_1643383030520.png' },
  { id: 'gc3', label: 'Munchies', image: 'https://cdn.grofers.com/app/images/category/cms_images/icon/icon_cat_1073_v_3_500_1643383030597.png' },
  { id: 'gc4', label: 'Cold Drinks', image: 'https://cdn.grofers.com/app/images/category/cms_images/icon/icon_cat_11_v_3_500_1643383030635.png' },
  { id: 'gc5', label: 'Instant Food', image: 'https://cdn.grofers.com/app/images/category/cms_images/icon/icon_cat_15_v_3_500_1643383030588.png' },
  { id: 'gc6', label: 'Tea & Coffee', image: 'https://cdn.grofers.com/app/images/category/cms_images/icon/icon_cat_12_v_3_500_1643383030626.png' },
  { id: 'gc7', label: 'Bakery', image: 'https://cdn.grofers.com/app/images/category/cms_images/icon/icon_cat_16_v_3_500_1643383030671.png' },
  { id: 'gc8', label: 'Sweet Tooth', image: 'https://cdn.grofers.com/app/images/category/cms_images/icon/icon_cat_1483_v_3_500_1643383030644.png' },
  { id: 'gc9', label: 'Atta & Rice', image: 'https://cdn.grofers.com/app/images/category/cms_images/icon/icon_cat_13_v_3_500_1643383030538.png' },
  { id: 'gc10', label: 'Masala & Oil', image: 'https://cdn.grofers.com/app/images/category/cms_images/icon/icon_cat_19_v_3_500_1643383030557.png' },
  { id: 'gc11', label: 'Meat & Fish', image: 'https://cdn.grofers.com/app/images/category/cms_images/icon/icon_cat_1052_v_3_500_1643383030689.png' },
  { id: 'gc12', label: 'Baby Care', image: 'https://cdn.grofers.com/app/images/category/cms_images/icon/icon_cat_7_v_3_500_1643383030617.png' },
  { id: 'gc13', label: 'Pharma', image: 'https://cdn.grofers.com/app/images/category/cms_images/icon/icon_cat_110_v_3_500_1643383030653.png' },
  { id: 'gc14', label: 'Cleaning', image: 'https://cdn.grofers.com/app/images/category/cms_images/icon/icon_cat_18_v_3_500_1643383030573.png' },
  { id: 'gc15', label: 'Home Needs', image: 'https://cdn.grofers.com/app/images/category/cms_images/icon/icon_cat_1379_v_3_500_1643383030663.png' },
  { id: 'gc16', label: 'Personal Care', image: 'https://cdn.grofers.com/app/images/category/cms_images/icon/icon_cat_163_v_3_500_1643383030608.png' },
  { id: 'gc17', label: 'Pet Care', image: 'https://cdn.grofers.com/app/images/category/cms_images/icon/icon_cat_5_v_3_500_1643383030548.png' },
  { id: 'gc18', label: 'Paan Corner', image: 'https://cdn.grofers.com/app/images/category/cms_images/icon/icon_cat_1236_v_3_500_1643383030698.png' },
  { id: 'gc19', label: 'Sauces', image: 'https://cdn.grofers.com/app/images/category/cms_images/icon/icon_cat_9_v_3_500_1643383030608.png' },
  { id: 'gc20', label: 'Bath & Body', image: 'https://cdn.grofers.com/app/images/category/cms_images/icon/icon_cat_16_v_3_500_1643383030671.png' },
];

export const HEALTH_CONCERNS: QuickCategory[] = [
  { id: 'hc1', label: 'Diabetes', image: 'https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/c2a0598f-483c-48ff-9783-71e402aa28d3.png?format=auto' },
  { id: 'hc2', label: 'Heart Care', image: 'https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/a5c22533-7425-4031-9487-7ab16896821c.png?format=auto' },
  { id: 'hc3', label: 'Stomach', image: 'https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/ba953802-f311-471a-a82d-11c587e677c7.png?format=auto' },
  { id: 'hc4', label: 'Skin Care', image: 'https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/96f9ed8a-ba62-426c-bd66-d072521e8438.png?format=auto' },
];

export const FASHION_CATEGORIES_QUICK: QuickCategory[] = [
  { id: 'fc1', label: 'Men', image: 'https://img.freepik.com/free-photo/portrait-handsome-smiling-stylish-young-man-model-dressed-red-checkered-shirt-fashion-man-posing_158538-4914.jpg?w=360' },
  { id: 'fc2', label: 'Women', image: 'https://img.freepik.com/free-photo/young-beautiful-smiling-female-trendy-summer-white-dress-sexy-carefree-woman-posing-near-blue-wall-studio-positive-model-having-fun-cheerful_158538-25656.jpg?w=360' },
  { id: 'fc3', label: 'Kids', image: 'https://img.freepik.com/free-photo/full-shot-cool-kid-posing_23-2149954002.jpg?w=360' },
  { id: 'fc4', label: 'Footwear', image: 'https://img.freepik.com/free-photo/pair-trainers_144627-3800.jpg?w=360' },
  { id: 'fc5', label: 'Beauty', image: 'https://img.freepik.com/free-photo/close-up-portrait-beautiful-woman-with-red-lips_158538-4943.jpg?w=360' },
  { id: 'fc6', label: 'Watches', image: 'https://img.freepik.com/free-photo/elegant-watch-with-silver-golden-chain-isolated_181624-27080.jpg?w=360' },
];

export const FASHION_BRANDS: QuickCategory[] = [
  { id: 'fb1', label: 'PUMA', image: 'https://logo.clearbit.com/puma.com' },
  { id: 'fb2', label: 'NIKE', image: 'https://logo.clearbit.com/nike.com' },
  { id: 'fb3', label: 'H&M', image: 'https://logo.clearbit.com/hm.com' },
  { id: 'fb4', label: 'LEVI\'S', image: 'https://logo.clearbit.com/levi.com' },
  { id: 'fb5', label: 'ZARA', image: 'https://logo.clearbit.com/zara.com' },
];

// --- Mock Products ---

export const MOCK_PRODUCTS: Product[] = [
  // --- FOOD DELIVERY (20 mins) ---
  {
    id: 'f1',
    name: 'Hyderabadi Chicken Dum Biryani',
    description: 'Aromatic basmati rice cooked with tender chicken and spices.',
    details: 'Experience the authentic taste of Hyderabad with our Chicken Dum Biryani. Marinated in a secret blend of spices and layered with long-grain basmati rice, slow-cooked to perfection in a sealed pot (dum). Served with spicy Mirchi ka Salan and refreshing Raita.',
    seller: 'Biryani Blues',
    price: 350,
    originalPrice: 450,
    rating: 4.5,
    reviews: 1200,
    image: 'https://b.zmtcdn.com/data/pictures/chains/4/18617404/249154a4066063b36128038b32152a48_o2_featured_v2.jpg',
    category: CategoryType.FOOD_DELIVERY,
    restaurantName: 'Biryani Blues',
    cuisine: 'Biryani, North Indian',
    deliveryTime: '20 mins',
    discount: 22
  },
  {
    id: 'f2',
    name: 'Farmhouse Pizza',
    description: 'Delightful combination of onion, capsicum, tomato & grilled mushroom.',
    details: 'Loaded with fresh veggies like onion, capsicum, tomato, and grilled mushroom. Topped with 100% mozzarella cheese on a fresh dough base. Perfect for veggie lovers looking for a crunch in every bite.',
    seller: 'Oven Story',
    price: 499,
    rating: 4.2,
    reviews: 3400,
    image: 'https://b.zmtcdn.com/data/pictures/chains/1/18413621/0a11270278a5b78b6714041b61c94043_o2_featured_v2.jpg',
    category: CategoryType.FOOD_DELIVERY,
    restaurantName: 'Oven Story',
    cuisine: 'Pizza, Fast Food',
    deliveryTime: '20 mins',
    isVeg: true
  },
  {
    id: 'f3',
    name: 'Maharaja Mac Burger',
    description: 'Double decker toasted sesame bun with veg patties.',
    details: 'The King of burgers! Two corn and cheese patties, stacked with fresh lettuce, jalapeños, onions, cheese slice, and creamy cocktail sauce, all in a triple-decker toasted sesame bun.',
    seller: 'McDonald\'s',
    price: 249,
    rating: 4.6,
    reviews: 5000,
    image: 'https://b.zmtcdn.com/data/pictures/chains/0/18260420/215b28c50c18400030232462e73f9828_o2_featured_v2.jpg',
    category: CategoryType.FOOD_DELIVERY,
    restaurantName: 'McDonald\'s',
    cuisine: 'Burger, Fast Food',
    deliveryTime: '20 mins',
  },
  {
    id: 'f4',
    name: 'McSpicy Paneer Burger',
    description: 'Crispy and spicy paneer patty.',
    details: 'Crispy and spicy paneer patty with creamy tandoori sauce and crispy lettuce. A favorite for vegetarians.',
    seller: 'McDonald\'s',
    price: 199,
    rating: 4.3,
    reviews: 1500,
    image: 'https://b.zmtcdn.com/data/dish_images/ccb7dc653753e83d63065d7f495a8c101639733140.png',
    category: CategoryType.FOOD_DELIVERY,
    restaurantName: 'McDonald\'s',
    cuisine: 'Burger, Fast Food',
    deliveryTime: '20 mins',
    isVeg: true
  },
  {
    id: 'f5',
    name: 'Chicken 65',
    description: 'Spicy, deep-fried chicken starter.',
    details: 'Chicken 65 is a spicy, deep-fried chicken dish originating from Hotel Buhari, Chennai. A perfect appetizer.',
    seller: 'Biryani Blues',
    price: 289,
    rating: 4.2,
    reviews: 600,
    image: 'https://b.zmtcdn.com/data/dish_images/1437bc204cb5c892cb22d78b4347f4651634827140.png',
    category: CategoryType.FOOD_DELIVERY,
    restaurantName: 'Biryani Blues',
    cuisine: 'Biryani, North Indian',
    deliveryTime: '20 mins',
  },
  {
    id: 'f6',
    name: 'Molten Chocolate Bear',
    description: 'Gooey chocolate cake.',
    details: 'Choco Lava Cake with a gooey chocolate center. The perfect end to your meal.',
    seller: 'Oven Story',
    price: 99,
    rating: 4.6,
    reviews: 1200,
    image: 'https://b.zmtcdn.com/data/dish_images/d5ab931c8c239271de45e1c159af94311634805744.png',
    category: CategoryType.FOOD_DELIVERY,
    restaurantName: 'Oven Story',
    cuisine: 'Desserts',
    deliveryTime: '20 mins',
    isVeg: true
  },
  
  // --- GROCERY (Quick Mart - 20 mins) ---
  {
    id: 'g1',
    name: 'Organic Bananas',
    description: 'Fresh organic bananas.',
    details: 'Sweet, ripe, and chemical-free organic bananas. Perfect for a healthy snack, smoothies, or baking. Sourced directly from certified organic farms.',
    seller: 'Spire Fresh',
    price: 60,
    rating: 4.8,
    reviews: 120,
    image: 'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/353066a.jpg',
    category: CategoryType.GROCERY,
    weight: '6 pcs',
    deliveryTime: '20 mins',
    discount: 0
  },
  {
    id: 'g2',
    name: 'Amul Taaza Fresh Milk',
    description: 'Pasteurized toned milk.',
    details: 'Amul Taaza is fresh toned milk, pasteurized to retain freshness and quality. Needs no boiling. Rich in calcium and protein.',
    seller: 'Super Mart',
    price: 32,
    rating: 4.9,
    reviews: 500,
    image: 'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/19512a.jpg',
    category: CategoryType.GROCERY,
    weight: '500 ml',
    deliveryTime: '20 mins',
  },
  {
    id: 'g3',
    name: 'Fortune Sunlite Refined Oil',
    description: 'Healthy refined sunflower oil.',
    details: 'Fortune Sunlite Refined Sunflower Oil is light, healthy, and easy to digest. Rich in vitamins and natural antioxidants, making it a healthy choice for your daily cooking.',
    seller: 'Fortune India',
    price: 145,
    rating: 4.7,
    reviews: 200,
    image: 'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/238a.jpg',
    category: CategoryType.GROCERY,
    weight: '1 L',
    deliveryTime: '20 mins',
    discount: 5
  },
  {
    id: 'g4',
    name: 'Lays India\'s Magic Masala',
    description: 'Spicy ruffled potato chips.',
    details: 'Made with the best quality potatoes and seasoned with the magic of Indian spices. A perfect crunchy snack for any time of the day.',
    seller: 'PepsiCo',
    price: 20,
    rating: 4.8,
    reviews: 1000,
    image: 'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/19088a.jpg',
    category: CategoryType.GROCERY,
    weight: '50g',
    deliveryTime: '20 mins',
  },

  // --- PHARMACY (Meds - 30 mins) ---
  {
    id: 'ph1',
    name: 'Tata 1mg Multivitamin Supreme',
    description: 'Zinc, Calcium & Vitamin D for immunity.',
    details: 'A comprehensive multivitamin supplement enriched with Zinc, Calcium, and Vitamin D. Helps boost immunity, improve energy levels, and support overall health. Daily wellness in a capsule.',
    seller: 'Tata 1mg Healthcare',
    price: 499,
    originalPrice: 750,
    rating: 4.8,
    reviews: 500,
    image: 'https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/351658428266453187216a6557618956.jpg',
    category: CategoryType.PHARMACY,
    deliveryTime: '30 mins',
    safeLogo: true,
    discount: 33
  },
  {
    id: 'ph2',
    name: 'Volini Pain Relief Gel',
    description: 'Quick relief from back pain and muscle sprain.',
    details: 'Volini Gel is a pain relief gel that provides effective relief from muscle pain, strains, sprains, spasms, and cramps. Scientifically formulated for quick absorption and deep penetration.',
    seller: 'Sun Pharma',
    price: 145,
    rating: 4.5,
    reviews: 230,
    image: 'https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/cropped/baf21876-0f8a-406a-a114-6b71891b65e9.jpg',
    category: CategoryType.PHARMACY,
    deliveryTime: '30 mins',
    discount: 10
  },
  {
    id: 'ph3',
    name: 'Accu-Chek Active Test Strips',
    description: 'Blood glucose testing strips.',
    details: 'Accu-Chek Active Test Strips are designed for easy and accurate blood glucose testing. Compatible with Accu-Chek Active glucometer. Requires a small blood sample and gives results in seconds.',
    seller: 'Roche Diabetes Care',
    price: 950,
    rating: 4.9,
    reviews: 800,
    image: 'https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/cropped/5863c01c-648c-4f7f-a634-19036b000212.png',
    category: CategoryType.PHARMACY,
    deliveryTime: '30 mins',
    requiresPrescription: false
  },

  // --- ELECTRONICS (Tech & Appliances - 30 mins) ---
  {
    id: 'e1',
    name: 'Apple iPhone 15 Pro',
    description: 'Titanium design, A17 Pro chip, 48MP Main Camera.',
    details: 'The iPhone 15 Pro features a strong and lightweight aerospace-grade titanium design with a textured matte-glass back. It also features a Ceramic Shield front that’s tougher than any smartphone glass. And it’s splash, water, and dust resistant.',
    seller: 'Appario Retail Pvt Ltd',
    price: 134900,
    rating: 4.9,
    reviews: 1500,
    image: 'https://m.media-amazon.com/images/I/81+GIkwqLIL._AC_SL1500_.jpg',
    category: CategoryType.ELECTRONICS,
    deliveryTime: '30 mins',
    isPrime: true,
    discount: 5,
    colors: ['#888887', '#253046', '#F5F5F0', '#000000'] // Natural, Blue, White, Black Titanium
  },
  {
    id: 'e2',
    name: 'Sony WH-1000XM5 Headphones',
    description: 'Industry leading noise canceling, 30hr battery.',
    details: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones. Features industry-leading noise cancellation with two processors and eight microphones. Enjoy up to 30 hours of battery life and quick charging.',
    seller: 'Electronics Bazaar',
    price: 29990,
    originalPrice: 34990,
    rating: 4.8,
    reviews: 2200,
    image: 'https://m.media-amazon.com/images/I/51SKmu2G9FL._AC_SL1000_.jpg',
    category: CategoryType.ELECTRONICS,
    deliveryTime: '30 mins',
    isPrime: true,
    discount: 13,
    colors: ['#000000', '#E5E4E2'] // Black, Silver
  },
  {
    id: 'e3',
    name: 'MacBook Air M2',
    description: '13.6-inch Liquid Retina display, 8GB RAM, 256GB SSD.',
    details: 'Supercharged by the M2 chip, MacBook Air is strikingly thin and brings exceptional speed and power efficiency within its durable all-aluminum enclosure. It’s the ultra-portable, ultra-capable laptop that lets you work, play, or create just about anything — anywhere.',
    seller: 'Apple India',
    price: 99900,
    rating: 4.9,
    reviews: 800,
    image: 'https://m.media-amazon.com/images/I/710TJuHTMhL._AC_SL1500_.jpg',
    category: CategoryType.ELECTRONICS,
    deliveryTime: '30 mins',
    isPrime: true,
    colors: ['#1D1D1F', '#F9F6F2', '#7D7E80', '#E3E4E5'] // Midnight, Starlight, Space Grey, Silver
  },
  {
    id: 'e4',
    name: 'Sony Bravia 55" 4K Ultra HD Smart LED Google TV',
    description: 'KD-55X74L | 4K HDR, Google TV, Open Baffle Speaker.',
    details: 'Experience thrilling games and movies in 4K resolution. The X1 4K Processor delivers lifelike color and contrast. Google TV brings together movies, shows, and more from across your apps and subscriptions.',
    seller: 'Electronics Bazaar',
    price: 57990,
    originalPrice: 99900,
    rating: 4.8,
    reviews: 3400,
    image: 'https://m.media-amazon.com/images/I/81wxS8abrgL._AC_SL1500_.jpg',
    category: CategoryType.ELECTRONICS,
    deliveryTime: '30 mins',
    isPrime: true,
    discount: 42,
    brand: 'Sony'
  },
  {
    id: 'e5',
    name: 'Samsung 138 cm (55 inches) Crystal iSmart 4K Ultra HD Smart LED TV',
    description: 'UA55CUE60AKLXL | Crystal Processor 4K, Tizen OS.',
    details: 'One billion true colors with Crystal Processor 4K. Smart Hub for all your content. OTS Lite for 3D surround sound experience.',
    seller: 'Samsung India',
    price: 45990,
    originalPrice: 64900,
    rating: 4.6,
    reviews: 1200,
    image: 'https://m.media-amazon.com/images/I/81+5Qe9ip8L._AC_SL1500_.jpg',
    category: CategoryType.ELECTRONICS,
    deliveryTime: '30 mins',
    discount: 29,
    brand: 'Samsung'
  },
  {
    id: 'e6',
    name: 'iPad Air (5th Gen)',
    description: 'M1 chip, 10.9-inch Liquid Retina display, 64GB.',
    details: 'iPad Air. With an immersive 10.9-inch Liquid Retina display. The breakthrough Apple M1 chip delivers faster performance, making iPad Air a creative and mobile gaming powerhouse.',
    seller: 'Apple India',
    price: 54900,
    rating: 4.8,
    reviews: 900,
    image: 'https://m.media-amazon.com/images/I/71VbHaAqbML._AC_SL1500_.jpg',
    category: CategoryType.ELECTRONICS,
    deliveryTime: '30 mins',
    isPrime: true,
    colors: ['#28282B', '#E3E4E5', '#E6C7C2', '#939597', '#B9B8D3'] // Space Grey, Starlight, Pink, Purple, Blue
  },
  {
    id: 'e7',
    name: 'JBL Flip 6 Wireless Bluetooth Speaker',
    description: 'IP67 Waterproof, 12 Hours Playtime.',
    details: 'Bold sound for every adventure. The JBL Flip 6 delivers powerful JBL Original Pro Sound with exceptional clarity thanks to its 2-way speaker system.',
    seller: 'Harman International',
    price: 11999,
    originalPrice: 14999,
    rating: 4.5,
    reviews: 5000,
    image: 'https://m.media-amazon.com/images/I/71J1sE+k3lL._AC_SL1500_.jpg',
    category: CategoryType.ELECTRONICS,
    deliveryTime: '30 mins',
    discount: 20,
    colors: ['#000000', '#0000FF', '#FF0000', '#008000']
  },
  {
    id: 'e8',
    name: 'Samsung 253 L 3 Star Inverter Double Door Refrigerator',
    description: 'Frost Free, Convertible 5-in-1 Digital Inverter.',
    details: 'Enjoy fresh food for longer with the Samsung 253L Double Door Refrigerator. Features Twin Cooling Plus technology and 5 conversion modes to suit your needs.',
    seller: 'Samsung India',
    price: 26990,
    originalPrice: 34990,
    rating: 4.5,
    reviews: 2100,
    image: 'https://m.media-amazon.com/images/I/716B19+LhNL._AC_SL1500_.jpg',
    category: CategoryType.ELECTRONICS,
    deliveryTime: '30 mins',
    discount: 23,
    brand: 'Samsung'
  },
  {
    id: 'e9',
    name: 'LG 7 Kg 5 Star Fully-Automatic Front Load Washing Machine',
    description: 'Direct Drive Technology, Steam Wash.',
    details: 'LG 7 Kg Front Load provides the best wash quality with 6 Motion Direct Drive technology. Steam wash removes allergens and bacteria. Energy efficient 5-star rating.',
    seller: 'LG Electronics',
    price: 29990,
    originalPrice: 38990,
    rating: 4.7,
    reviews: 1500,
    image: 'https://m.media-amazon.com/images/I/712B4P3yK4L._AC_SL1500_.jpg',
    category: CategoryType.ELECTRONICS,
    deliveryTime: '30 mins',
    discount: 23,
    brand: 'LG'
  },
  {
    id: 'e10',
    name: 'IFB 30 L Convection Microwave Oven',
    description: '30BRC2, Rotisserie, Auto Cook Menus.',
    details: 'Become a master chef with the IFB 30L Convection Microwave. Features 101 auto cook menus, steam clean, and rotisserie for perfect grilling.',
    seller: 'IFB Industries',
    price: 15490,
    originalPrice: 19990,
    rating: 4.4,
    reviews: 950,
    image: 'https://m.media-amazon.com/images/I/81D8pNF00EL._AC_SL1500_.jpg',
    category: CategoryType.ELECTRONICS,
    deliveryTime: '30 mins',
    discount: 22,
    brand: 'IFB'
  },
  {
    id: 'e11',
    name: 'Daikin 1.5 Ton 5 Star Inverter Split AC',
    description: 'PM 2.5 Filter, 3D Airflow, Dew Clean Technology.',
    details: 'Beat the heat with Daikin 1.5 Ton Split AC. Features Neo Swing Inverter Compressor for quiet operation and Econo mode for power saving.',
    seller: 'Daikin Airconditioning',
    price: 45490,
    originalPrice: 67200,
    rating: 4.6,
    reviews: 800,
    image: 'https://m.media-amazon.com/images/I/51w1+O2oKlL._AC_SL1024_.jpg',
    category: CategoryType.ELECTRONICS,
    deliveryTime: '30 mins',
    discount: 32,
    brand: 'Daikin'
  },
  {
    id: 'e12',
    name: 'Philips Digital Air Fryer HD9252/90',
    description: 'Rapid Air Technology, 90% Less Fat.',
    details: 'Delicious fries with up to 90% less fat! The Philips Air Fryer uses Rapid Air Technology to cook your favorite foods to crispy perfection with little or no oil.',
    seller: 'Philips India',
    price: 8999,
    originalPrice: 12995,
    rating: 4.7,
    reviews: 4000,
    image: 'https://m.media-amazon.com/images/I/61u9Fw+5RkL._AC_SL1000_.jpg',
    category: CategoryType.ELECTRONICS,
    deliveryTime: '30 mins',
    discount: 31,
    brand: 'Philips'
  },

  // --- FASHION (30 mins) ---
  {
    id: 'fas1',
    name: 'Levi\'s Men\'s 511 Slim Fit Jeans',
    description: 'Stylish blue denim for everyday wear.',
    details: 'A modern slim with room to move, the 511 Slim Fit Jeans are a classic since right now. These jeans sit below the waist with a slim fit from hip to ankle. Made with Water<Less techniques that reduce the use of water in the garment manufacturing process.',
    seller: 'RetailNet',
    price: 2499,
    originalPrice: 4999,
    rating: 4.4,
    reviews: 320,
    image: 'https://m.media-amazon.com/images/I/616x+yT1VIL._AC_UY1000_.jpg',
    category: CategoryType.FASHION,
    deliveryTime: '30 mins',
    isPrime: true,
    brand: "LEVI'S",
    discount: 50,
    sizes: ['28', '30', '32', '34', '36'],
    colors: ['#1F2937', '#3B82F6', '#6B7280'] // Dark Grey, Blue, Grey
  },
  {
    id: 'fas2',
    name: 'Nike Air Max SC',
    description: 'Old school look with modern comfort.',
    details: 'With its easygoing lines, heritage track look and of course, visible Air cushioning, the Nike Air Max SC is the perfect finish to any outfit. The rich mixture of materials adds depth while making it a durable and lightweight shoe for everyday wear.',
    seller: 'Nike India',
    price: 6995,
    originalPrice: 8995,
    rating: 4.7,
    reviews: 890,
    image: 'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/3396ee3c-08cc-4ada-baa9-655af12e3120/air-max-sc-mens-shoes-1V8V12.png',
    category: CategoryType.FASHION,
    deliveryTime: '30 mins',
    discount: 15,
    brand: 'NIKE',
    sizes: ['UK 6', 'UK 7', 'UK 8', 'UK 9', 'UK 10'],
    colors: ['#FFFFFF', '#000000']
  },
  {
    id: 'fas3',
    name: 'H&M Cotton T-Shirt',
    description: 'Regular fit cotton t-shirt in white.',
    details: 'T-shirt in soft cotton jersey with a ribbed crew neck and straight hem. Regular fit for comfortable wear.',
    seller: 'H&M Hennes & Mauritz Retail',
    price: 399,
    rating: 4.2,
    reviews: 1200,
    image: 'https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2Fbc%2F40%2Fbc40097c006842750e3352701f81d8502288ba2b.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5Bmen_tshirtstanks_shortsleeve%5D%2Ctype%5BDESCRIPTIVESTILLLIFE%5D%2Cres%5Bm%5D%2Chmver%5B2%5D&call=url[file:/product/main]',
    category: CategoryType.FASHION,
    deliveryTime: '30 mins',
    brand: 'H&M',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['#FFFFFF', '#000000', '#10B981', '#EF4444'] // White, Black, Green, Red
  },
  {
    id: 'fas4',
    name: 'Puma Running Shoes',
    description: 'Softride Enzo NXT Running Shoes.',
    details: 'The Softride Enzo NXT combines two of Puma\'s key franchises - Softride and Enzo. Utilizing Softride EVA technology that provides extreme cushioning and all-day comfort, and showcasing a progressive upper design language.',
    seller: 'Puma Sports India',
    price: 3499,
    originalPrice: 5999,
    rating: 4.5,
    reviews: 450,
    image: 'https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/195234/01/sv01/fnd/IND/fmt/png/Softride-Enzo-NXT-Men',
    category: CategoryType.FASHION,
    deliveryTime: '30 mins',
    brand: 'PUMA',
    discount: 40,
    sizes: ['UK 6', 'UK 7', 'UK 8', 'UK 9', 'UK 10'],
    colors: ['#DC2626', '#000000'] // Red, Black
  },

  // --- BEAUTY (30 mins) ---
  {
    id: 'b1',
    name: 'Maybelline New York Fit Me Foundation',
    description: 'Matte + Poreless Liquid Foundation.',
    details: 'Maybelline Fit Me Matte + Poreless Liquid Foundation is a lightweight foundation that mattifies and refines pores and leaves a natural, seamless finish.',
    seller: 'Nykaa E-Retail',
    price: 549,
    originalPrice: 649,
    rating: 4.5,
    reviews: 15000,
    image: 'https://images-static.nykaa.com/media/catalog/product/d/5/d51e73924716_H_8901526584109.jpg',
    category: CategoryType.BEAUTY,
    deliveryTime: '30 mins',
    discount: 15,
    brand: 'Maybelline',
    colors: ['#F3D2B5', '#E4C1A9', '#D1A384'] // Ivory, Beige, Sun
  },
  {
    id: 'b2',
    name: 'L\'Oreal Paris Paris Revitalift Serum',
    description: 'Hyaluronic Acid Serum for plumping.',
    details: 'L\'Oreal Paris Revitalift 1.5% Hyaluronic Acid Serum. Lightweight and non-sticky serum that instantly hydrates and leaves skin radiant and glowing.',
    seller: 'L\'Oreal India',
    price: 899,
    originalPrice: 999,
    rating: 4.7,
    reviews: 5000,
    image: 'https://images-static.nykaa.com/media/catalog/product/tr:w-220,h-220,cm-pad_resize/c/4/c43a6d7LOREA00000002_1.jpg',
    category: CategoryType.BEAUTY,
    deliveryTime: '30 mins',
    discount: 10,
    brand: 'L\'Oreal'
  },

  // --- HOME & KITCHEN (30 mins) ---
  {
    id: 'h1',
    name: 'Prestige Iris Mixer Grinder',
    description: '750 Watt, 3 Jars + 1 Juicer Jar.',
    details: 'Prestige Iris 750 Watt Mixer Grinder with 3 Stainless Steel Jars and 1 Juicer Jar. Powerful motor for heavy duty grinding. Ergonomic handle and overload protection.',
    seller: 'Cloudtail India',
    price: 3299,
    originalPrice: 6195,
    rating: 4.2,
    reviews: 21000,
    image: 'https://m.media-amazon.com/images/I/61+C+H3LgOL._AC_SL1500_.jpg',
    category: CategoryType.HOME,
    deliveryTime: '30 mins',
    discount: 47,
    brand: 'Prestige'
  },
  {
    id: 'h2',
    name: 'Milton Thermosteel Flask',
    description: '1000ml Vacuum Insulated Bottle.',
    details: 'Milton Thermosteel Flip Lid Flask, 1000ml. Keeps beverages hot or cold for 24 hours. Made of high quality stainless steel.',
    seller: 'RetailNet',
    price: 850,
    originalPrice: 1190,
    rating: 4.6,
    reviews: 8000,
    image: 'https://m.media-amazon.com/images/I/610tM3tL0ZL._AC_SL1500_.jpg',
    category: CategoryType.HOME,
    deliveryTime: '30 mins',
    discount: 28,
    colors: ['#C0C0C0', '#000000']
  },

  // --- TOYS & BABY (30 mins) ---
  {
    id: 't1',
    name: 'LEGO Classic Creative Bricks',
    description: 'Building Kit with 484 pieces.',
    details: 'Unleash a world of open-ended creativity and imagination with the LEGO Classic Creative Brick Box. Construction play for children.',
    seller: 'Hamleys',
    price: 4999,
    rating: 4.9,
    reviews: 1200,
    image: 'https://m.media-amazon.com/images/I/815z8t4jCFL._AC_SL1500_.jpg',
    category: CategoryType.TOYS,
    deliveryTime: '30 mins',
    brand: 'LEGO'
  }
];

export const CATEGORIES = [
  { id: CategoryType.FASHION, label: 'Fashion', icon: <Shirt className="w-5 h-5 text-pink-600" />, color: 'bg-pink-50' },
  { id: CategoryType.FOOD_DELIVERY, label: 'Food', icon: <Utensils className="w-5 h-5 text-red-500" />, color: 'bg-red-50' },
  { id: CategoryType.GROCERY, label: 'Quick Mart', icon: <Zap className="w-5 h-5 text-yellow-500" />, color: 'bg-yellow-50' },
  { id: CategoryType.PHARMACY, label: 'Pharmacy', icon: <Activity className="w-5 h-5 text-teal-500" />, color: 'bg-teal-50' },
  { id: CategoryType.ELECTRONICS, label: 'Tech', icon: <Smartphone className="w-5 h-5 text-blue-500" />, color: 'bg-blue-50' },
  { id: CategoryType.BEAUTY, label: 'Beauty', icon: <Sparkles className="w-5 h-5 text-purple-500" />, color: 'bg-purple-50' },
  { id: CategoryType.HOME, label: 'Home', icon: <Home className="w-5 h-5 text-orange-500" />, color: 'bg-orange-50' },
  { id: CategoryType.TOYS, label: 'Toys', icon: <Gamepad2 className="w-5 h-5 text-indigo-500" />, color: 'bg-indigo-50' },
];